openapi: 3.0.0
servers: []
info:
  title: Serverless Beacon API
  version: 0.1.0
  description:
    Provides an API for contributing to and querying a serverless ga4gh beacon
    instance.
  contact:
    email: brendan.hosking@csiro.au
externalDocs:
  description: Beacon Project
  url: 'http://beacon-project.io/'
paths:
  /:
    summary: Get information about the beacon
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Beacon'
    options:
      responses:
        200:
          description: OK

components:
  schemas:
    Beacon:
      type: object
      required:
        - id
        - name
        - apiVersion
        - organization
        - datasets
      properties:
        id:
          type: string
          description: Unique identifier of the beacon. Use reverse domain name
            notation.
          example: org.ga4gh.beacon
        apiVersion:
          type: string
          description: Version of the API provided by the beacon.
          example: v1.0.0
        organization:
          $ref: '#/components/schemas/BeaconOrganization'
        datasets:
          description: Dataset(s) served by the beacon.
          type: array
          items:
            $ref: '#/components/schemas/BeaconDataset'
    BeaconDataset:
      type: object
      required:
        - id
        - name
        - assemblyId
        - createDateTime
        - updateDateTime
      properties:
        id:
          type: string
          description: Unique identifier of the dataset.
        name:
          type: string
          description: Name of the dataset.
        description:
          type: string
          description: Description of the dataset.
        assemblyId:
          description: 'Assembly identifier (GRC notation, e.g. `GRCh37`).'
          type: string
          example: GRCh38
        createDateTime:
          type: string
          description: The time the dataset was created (ISO 8601 format).
          example: '2012-07-29 or 2017-01-17T20:33:40'
        updateDateTime:
          type: string
          description: The time the dataset was updated in (ISO 8601 format).
          example: '2012-07-19 or 2017-01-17T20:33:40'
        version:
          type: string
          description: Version of the dataset.
        variantCount:
          type: integer
          format: int64
          description: Total number of variants in the dataset.
          minimum: 0
        callCount:
          type: integer
          format: int64
          description: Total number of calls in the dataset.
          minimum: 0
        sampleCount:
          type: integer
          format: int64
          description: Total number of samples in the dataset.
          minimum: 0
        externalUrl:
          type: string
          description:
            URL to an external system providing more dataset information (RFC
            3986 format).
          example: 'http://example.org/wiki/Main_Page'
        info:
          description: Additional structured metadata, key-value pairs.
          type: array
          items:
            type: object
        dataUseConditions:
          description: Data use conditions ruling this dataset.
          type: object
    BeaconDatasetAlleleResponse:
      type: object
      required:
        - datasetId
      properties:
        datasetId:
          type: string
          description: not provided
        exists:
          description: >-
            Indicator of whether the given allele was observed in the dataset.
            This should be non-null, unless there was an error, in which case
            `error` has to be non-null.
          type: boolean
        error:
          $ref: '#/components/schemas/BeaconError'
        frequency:
          type: number
          description: Frequency of this allele in the dataset. Between 0 and 1,
            inclusive.
          minimum: 0
          maximum: 1
        variantCount:
          type: integer
          description: Number of variants matching the allele request in the dataset.
          minimum: 0
        callCount:
          type: integer
          description: Number of calls matching the allele request in the dataset.
          minimum: 0
        sampleCount:
          type: integer
          description: Number of samples matching the allele request in the dataset
          minimum: 0
        note:
          type: string
          description: Additional note or description of the response.
        externalUrl:
          type: string
          description: >-
            URL to an external system, such as a secured beacon or a system
            providing more information about a given allele (RFC 3986 format).
        info:
          description: Additional structured metadata, key-value pairs.
          type: array
          items:
            type: object
    BeaconError:
      description: >-
        Beacon-specific error. This should be non-null in exceptional situations
        only, in which case `exists` has to be null.
      type: object
      required:
        - errorCode
      properties:
        errorCode:
          type: integer
          format: int32
        errorMessage:
          type: string
    BeaconOrganization:
      description: Organization owning the beacon.
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          description: Unique identifier of the organization.
        name:
          type: string
          description: Name of the organization.
